
const GET_MOST_FORKED_REPOS_REQUEST = 'GET_MOST_FORKED_REPOS_REQUEST';
const GET_MOST_FORKED_REPOS_SUCCESS = 'GET_MOST_FORKED_REPOS_SUCCESS';
const GET_MOST_FORKED_REPOS_FAILURE = 'GET_MOST_FORKED_REPOS_FAILURE';


export{
	GET_MOST_FORKED_REPOS_REQUEST,
	GET_MOST_FORKED_REPOS_SUCCESS,
	GET_MOST_FORKED_REPOS_FAILURE
}
